name: build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [simmer]

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest, r: 'devel'}
        - {os: macOS-latest, r: 'release'}
        - {os: windows-latest, r: 'release'}
        - {os: ubuntu-latest, r: 'release'}
        - {os: ubuntu-latest, r: 'oldrel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Configure git
      if: ${{ runner.os == 'Windows' }}
      run: git config --global core.symlinks false

    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.config.r }}
    - uses: r-lib/actions/setup-pandoc@v1

    - name: Query dependencies
      run: |
        install.packages('remotes')
        saveRDS(remotes::dev_package_deps(dependencies=TRUE), ".github/depends.Rds", version=2)
      shell: Rscript {0}

    - name: Cache R packages
      if: ${{ runner.os != 'Windows' }}
      uses: actions/cache@v1
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-1-

    - name: Install Linux dependencies
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install devscripts libcurl4-openssl-dev

    - name: Install dependencies
      run: |
        remotes::install_github("r-simmer/simmer")
        remotes::install_deps(dependencies=TRUE)
        remotes::install_cran(c("rcmdcheck", "covr"))
      shell: Rscript {0}

    - name: Check
      run: |
        unlink("docs", force=TRUE)
        rcmdcheck::rcmdcheck(args=c("--no-manual", "--as-cran"),
          error_on="warning", check_dir="check")
      shell: Rscript {0}

    - name: Upload check results
      if: ${{ failure() }}
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
        path: check

    - name: Test coverage
      if: ${{ success() && matrix.config.covr == 'yes' }}
      run: covr::codecov()
      shell: Rscript {0}
